### ISSUE TITLE
Crawl-Delay support?

### ISSUE THREAD

**Issue by fluffy-critter** [google/robotstxt#33]
There's a commonly-supported optional field, [`Crawl-Delay`](https://en.wikipedia.org/wiki/Robots_exclusion_standard#Crawl-delay_directive), which indicates the requested minimum time between bot requests on a site. It would be really nice if this library could parse that and provide a function to query the crawl delay for a specified user-agent.

**Comment by garyillyes** [comment]
Crawl-Delay is not commonly supported, in fact no search engine I can think of fully supports it. The only fields that we can support are already documented (allow, disallow, user-agent), but if you need to support other fields in your own port, we also included an example (sitemap) of how to parse other fields.
