### ISSUE TITLE
CMAKE_CXX_STANDARD 14

### ISSUE THREAD

**Issue by dbugger29** [google/robotstxt#54]
can you please upgrade the [CMAKE_CXX_STANDARD to 14](https://github.com/google/robotstxt/blob/master/CMakeLists.txt#L4)?
It is required now by [abseil-cpp](https://github.com/abseil/abseil-cpp/commit/97ab3dcfd6490434202e4ab00b2eaba9449e42a1)

Thank you

**Comment by garyillyes** [comment]
Thanks for letting us know. Upgraded CMAKE_CXX_STANDARD to 14 in https://github.com/google/robotstxt/commit/d23aab3f418515dfc475032c52f8e26948fda7f9
