### ISSUE TITLE
Update README build requirements

### ISSUE THREAD

**Issue by Gianlo98** [google/robotstxt#55]
The README says that we should have installed a compatible C++ compiler supporting **at least C++11**, but once I ran tests, I got an error saying that C++ versions **less than C++14 are not supported**.

**Comment by hassanrazakhalid** [comment]
Yes i can not follow docs using ubuntu 20. Here is my output
```

g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
