### ISSUE TITLE
User-agent names in test ID_UserAgentValueCaseInsensitive to follow the standard

### ISSUE THREAD

**Issue by sebastian-nagel** [google/robotstxt#56]
The robots.txt in test "ID_UserAgentValueCaseInsensitive" ([robots_test.cc, line 200](https://github.com/google/robotstxt/blob/455b1583103d13ad88fe526bc058d6b9f3309215/robots_test.cc#L200)) uses user-agent names violating the standard as they include a white space (`FOO BAR`, `foo bar`, `FoO bAr`). User-agent names in the test are matched up to the first white space - a Google-specific feature following the comments in [test GoogleOnly_AcceptUserAgentUpToFirstSpace](https://github.com/google/robotstxt/blob/455b1583103d13ad88fe526bc058d6b9f3309215/robots_test.cc#L230). What about using standard-conform names in the user-agent directives? Eg. `FOO` or `FOOBAR`?

**Comment by garyillyes** [comment]
Hi Sebastian,

Matching up to the first space (it's actually up to the first invalid character OR EOL) is defined by the RFC and it's not Google specific. See https://www.rfc-editor.org/rfc/rfc9309.html#name-formal-syntax

`identifier = 1*(%x2D / %x41-5A / %x5F / %x61-7A)`

The test case on line 200 is also preceded by test cases for valid (as per RFC) product tokens.

**Comment by garyillyes** [comment]
> Does the formal syntax in section 2.2 really allow arbitrary characters after the user-agent identifier - apart from white space or a comment?

Weeell, it's actually 2.3.1.5 that demands it: https://www.rfc-editor.org/rfc/rfc9309.html#section-2.3.1.5

**Comment by sebastian-nagel** [comment]
Thanks again for the clarification! I'm ok to close this issue...

**Comment by garyillyes** [comment]
Cool! Thanks for the chat :)
