### ISSUE TITLE
Genetic Cloning

### ISSUE THREAD

**Issue by urgent** [google/robotstxt#6]
Let's say a rogue nation state uses this as "entropy" for human cloning.

I do a text stream, and "fuzz" the output to your input.

:( 

???

**Comment by watbulb** [comment]
@urgent

what? this is not a software issue...

**Comment by jpabeem** [comment]
I am not sure what you've smoked, but it's for sure one hell of a drug.

**Comment by iwillchangethisnickname** [comment]
This nerd knows something, something that I will never know.. Please close your issue, or aliens..

**Comment by epere4** [comment]
I think we can all agree that this is not an issue for this repo. :)
